a = str(input("Hi, Bro. How are you?\n>>> "))

#good fillings

#good

if a == "good": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "gooD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "goOd": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "goOD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "gOod": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "gOoD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "gOOd": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "gOOD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "Good": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GooD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GoOd": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GoOD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GOod": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GOoD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GOOd": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "GOOD": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")

#nice

elif a == "nice": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "nicE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "niCe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "niCE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "nIce": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "nIcE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "nICe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "nICE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "Nice": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NicE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NiCe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NiCE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NIce": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NIcE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NICe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "NICE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")

#cool

elif a == "cool": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "cooL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "coOl": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "coOL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "cOol": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "cOoL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "cOOl": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "cOOL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "Cool": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "CooL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "CoOl": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "CoOL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "COol": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "COoL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "COOl": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "COOL": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")

#fun

elif a == "fun": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fuN": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fUn": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fUN": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "Fun": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FuN": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FUn": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FUN": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")

#fine

elif a == "fine": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "finE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fiNe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fiNE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fIne": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fInE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fINe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "fINE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "Fine": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FinE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FiNe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FiNE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FIne": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FInE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FINe": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")
elif a == "FINE": input("That's Cool! So, what question or piece of advice would you like to ask me?\n>>> ")

#Bad fillings

#bad

elif a == "bad": input("Oh, can you tell me what happend?")
elif a == "baD": input("Oh, can you tell me what happend?")
elif a == "bAd": input("Oh, can you tell me what happend?")
elif a == "bAD": input("Oh, can you tell me what happend?")
elif a == "Bad": input("Oh, can you tell me what happend?")
elif a == "BaD": input("Oh, can you tell me what happend?")
elif a == "BAd": input("Oh, can you tell me what happend?")
elif a == "BAD": input("Oh, can you tell me what happend?")

#poor: not good quality

elif a == "poor": input("Oh, can you tell me what happend?")
elif a == "pooR": input("Oh, can you tell me what happend?")
elif a == "poOr": input("Oh, can you tell me what happend?")
elif a == "poOR": input("Oh, can you tell me what happend?")
elif a == "pOor": input("Oh, can you tell me what happend?")
elif a == "pOoR": input("Oh, can you tell me what happend?")
elif a == "pOOr": input("Oh, can you tell me what happend?")
elif a == "pOOR": input("Oh, can you tell me what happend?")
elif a == "Poor": input("Oh, can you tell me what happend?")
elif a == "PooR": input("Oh, can you tell me what happend?")
elif a == "PoOr": input("Oh, can you tell me what happend?")
elif a == "PoOR": input("Oh, can you tell me what happend?")
elif a == "POor": input("Oh, can you tell me what happend?")
elif a == "POoR": input("Oh, can you tell me what happend?")
elif a == "POOr": input("Oh, can you tell me what happend?")
elif a == "POOR": input("Oh, can you tell me what happend?")

#awful: very bad

elif a == "awful": input("Oh, can you tell me what happend?")
elif a == "awfuL": input("Oh, can you tell me what happend?")
elif a == "awfUl": input("Oh, can you tell me what happend?")
elif a == "awfUL": input("Oh, can you tell me what happend?")
elif a == "awFul": input("Oh, can you tell me what happend?")
elif a == "awFuL": input("Oh, can you tell me what happend?")
elif a == "awFUl": input("Oh, can you tell me what happend?")
elif a == "awFUL": input("Oh, can you tell me what happend?")
elif a == "aWful": input("Oh, can you tell me what happend?")
elif a == "aWfuL": input("Oh, can you tell me what happend?")
elif a == "aWfUl": input("Oh, can you tell me what happend?")
elif a == "aWfUL": input("Oh, can you tell me what happend?")
elif a == "aWFul": input("Oh, can you tell me what happend?")
elif a == "aWFuL": input("Oh, can you tell me what happend?")
elif a == "aWFUl": input("Oh, can you tell me what happend?")
elif a == "aWFUL": input("Oh, can you tell me what happend?")
elif a == "Awful": input("Oh, can you tell me what happend?")
elif a == "AwfuL": input("Oh, can you tell me what happend?")
elif a == "AwfUl": input("Oh, can you tell me what happend?")
elif a == "AwfUL": input("Oh, can you tell me what happend?")
elif a == "AwFul": input("Oh, can you tell me what happend?")
elif a == "AwFuL": input("Oh, can you tell me what happend?")
elif a == "AwFUl": input("Oh, can you tell me what happend?")
elif a == "AwFUL": input("Oh, can you tell me what happend?")
elif a == "AWful": input("Oh, can you tell me what happend?")
elif a == "AWfuL": input("Oh, can you tell me what happend?")
elif a == "AWfUl": input("Oh, can you tell me what happend?")
elif a == "AWfUL": input("Oh, can you tell me what happend?")
elif a == "AWFul": input("Oh, can you tell me what happend?")
elif a == "AWFuL": input("Oh, can you tell me what happend?")
elif a == "AWFUl": input("Oh, can you tell me what happend?")
elif a == "AWFUL": input("Oh, can you tell me what happend?")

#lousy

elif a == "lousy": input("Oh, can you tell me what happend?")
elif a == "lousY": input("Oh, can you tell me what happend?")
elif a == "louSy": input("Oh, can you tell me what happend?")
elif a == "louSY": input("Oh, can you tell me what happend?")
elif a == "loUsy": input("Oh, can you tell me what happend?")
elif a == "loUsY": input("Oh, can you tell me what happend?")
elif a == "loUSy": input("Oh, can you tell me what happend?")
elif a == "loUSY": input("Oh, can you tell me what happend?")
elif a == "lOusy": input("Oh, can you tell me what happend?")
elif a == "lOusY": input("Oh, can you tell me what happend?")
elif a == "lOuSy": input("Oh, can you tell me what happend?")
elif a == "lOuSY": input("Oh, can you tell me what happend?")
elif a == "lOUsy": input("Oh, can you tell me what happend?")
elif a == "lOUsY": input("Oh, can you tell me what happend?")
elif a == "lOUSy": input("Oh, can you tell me what happend?")
elif a == "lOUSY": input("Oh, can you tell me what happend?")
elif a == "Lousy": input("Oh, can you tell me what happend?")
elif a == "LousY": input("Oh, can you tell me what happend?")
elif a == "LouSy": input("Oh, can you tell me what happend?")
elif a == "LouSY": input("Oh, can you tell me what happend?")
elif a == "LoUsy": input("Oh, can you tell me what happend?")
elif a == "LoUsY": input("Oh, can you tell me what happend?")
elif a == "LoUSy": input("Oh, can you tell me what happend?")
elif a == "LoUSY": input("Oh, can you tell me what happend?")
elif a == "LOusy": input("Oh, can you tell me what happend?")
elif a == "LOusY": input("Oh, can you tell me what happend?")
elif a == "LOuSy": input("Oh, can you tell me what happend?")
elif a == "LOuSY": input("Oh, can you tell me what happend?")
elif a == "LOUsy": input("Oh, can you tell me what happend?")
elif a == "LOUsY": input("Oh, can you tell me what happend?")
elif a == "LOUSy": input("Oh, can you tell me what happend?")
elif a == "LOUSY": input("Oh, can you tell me what happend?")

#wrong: not correct

elif a == "wrong": input("Oh, can you tell me what happend?")
elif a == "wronG": input("Oh, can you tell me what happend?")
elif a == "wroNg": input("Oh, can you tell me what happend?")
elif a == "wroNG": input("Oh, can you tell me what happend?")
elif a == "wrOng": input("Oh, can you tell me what happend?")
elif a == "wrOnG": input("Oh, can you tell me what happend?")
elif a == "wrONg": input("Oh, can you tell me what happend?")
elif a == "wrONG": input("Oh, can you tell me what happend?")
elif a == "wRong": input("Oh, can you tell me what happend?")
elif a == "wRonG": input("Oh, can you tell me what happend?")
elif a == "wRoNg": input("Oh, can you tell me what happend?")
elif a == "wRoNG": input("Oh, can you tell me what happend?")
elif a == "wROng": input("Oh, can you tell me what happend?")
elif a == "wROnG": input("Oh, can you tell me what happend?")
elif a == "wRONg": input("Oh, can you tell me what happend?")
elif a == "wRONG": input("Oh, can you tell me what happend?")
elif a == "Wrong": input("Oh, can you tell me what happend?")
elif a == "WronG": input("Oh, can you tell me what happend?")
elif a == "WroNg": input("Oh, can you tell me what happend?")
elif a == "WroNG": input("Oh, can you tell me what happend?")
elif a == "WrOng": input("Oh, can you tell me what happend?")
elif a == "WrOnG": input("Oh, can you tell me what happend?")
elif a == "WrONg": input("Oh, can you tell me what happend?")
elif a == "WrONG": input("Oh, can you tell me what happend?")
elif a == "WRong": input("Oh, can you tell me what happend?")
elif a == "WRonG": input("Oh, can you tell me what happend?")
elif a == "WRoNg": input("Oh, can you tell me what happend?")
elif a == "WRoNG": input("Oh, can you tell me what happend?")
elif a == "WROng": input("Oh, can you tell me what happend?")
elif a == "WROnG": input("Oh, can you tell me what happend?")
elif a == "WRONg": input("Oh, can you tell me what happend?")
elif a == "WRONG": input("Oh, can you tell me what happend?")

#faulty: not working property

elif a == "faulty": input("Oh, can you tell me what happend?")
elif a == "faultY": input("Oh, can you tell me what happend?")
elif a == "faulTy": input("Oh, can you tell me what happend?")
elif a == "faulTY": input("Oh, can you tell me what happend?")
elif a == "fauLty": input("Oh, can you tell me what happend?")
elif a == "fauLtY": input("Oh, can you tell me what happend?")
elif a == "fauLTy": input("Oh, can you tell me what happend?")
elif a == "fauLTY": input("Oh, can you tell me what happend?")
elif a == "faUlty": input("Oh, can you tell me what happend?")
elif a == "faUltY": input("Oh, can you tell me what happend?")
elif a == "faUlTy": input("Oh, can you tell me what happend?")
elif a == "faUlTY": input("Oh, can you tell me what happend?")
elif a == "faULty": input("Oh, can you tell me what happend?")
elif a == "faULtY": input("Oh, can you tell me what happend?")
elif a == "faULTy": input("Oh, can you tell me what happend?")
elif a == "faULTY": input("Oh, can you tell me what happend?")
elif a == "fAulty": input("Oh, can you tell me what happend?")
elif a == "fAultY": input("Oh, can you tell me what happend?")
elif a == "fAulTy": input("Oh, can you tell me what happend?")
elif a == "fAulTY": input("Oh, can you tell me what happend?")
elif a == "fAuLty": input("Oh, can you tell me what happend?")
elif a == "fAuLtY": input("Oh, can you tell me what happend?")
elif a == "fAuLTy": input("Oh, can you tell me what happend?")
elif a == "fAuLTY": input("Oh, can you tell me what happend?")
elif a == "fAUlty": input("Oh, can you tell me what happend?")
elif a == "fAUltY": input("Oh, can you tell me what happend?")
elif a == "FAUlTy": input("Oh, can you tell me what happend?")
elif a == "FAUlTY": input("Oh, can you tell me what happend?")
elif a == "FAULty": input("Oh, can you tell me what happend?")
elif a == "FAULtY": input("Oh, can you tell me what happend?")
elif a == "FAULTy": input("Oh, can you tell me what happend?")
elif a == "FAULTY": input("Oh, can you tell me what happend?")










