a = str(input("Hi, Bro. How are you?\n>>> "))

#good fillings

#good

if a == "good": print("That's Cool!")
elif a == "gooD": print("That's Cool!")
elif a == "goOd": print("That's Cool!")
elif a == "goOD": print("That's Cool!")
elif a == "gOod": print("That's Cool!")
elif a == "gOoD": print("That's Cool!")
elif a == "gOOd": print("That's Cool!")
elif a == "gOOD": print("That's Cool!")
elif a == "Good": print("That's Cool!")
elif a == "GooD": print("That's Cool!")
elif a == "GoOd": print("That's Cool!")
elif a == "GoOD": print("That's Cool!")
elif a == "GOod": print("That's Cool!")
elif a == "GOoD": print("That's Cool!")
elif a == "GOOd": print("That's Cool!")
elif a == "GOOD": print("That's Cool!")

#nice

elif a == "nice": print("That's Cool!")
elif a == "nicE": print("That's Cool!")
elif a == "niCe": print("That's Cool!")
elif a == "niCE": print("That's Cool!")
elif a == "nIce": print("That's Cool!")
elif a == "nIcE": print("That's Cool!")
elif a == "nICe": print("That's Cool!")
elif a == "nICE": print("That's Cool!")
elif a == "Nice": print("That's Cool!")
elif a == "NicE": print("That's Cool!")
elif a == "NiCe": print("That's Cool!")
elif a == "NiCE": print("That's Cool!")
elif a == "NIce": print("That's Cool!")
elif a == "NIcE": print("That's Cool!")
elif a == "NICe": print("That's Cool!")
elif a == "NICE": print("That's Cool!")

#cool

elif a == "cool": print("That's Cool!")
elif a == "cooL": print("That's Cool!")
elif a == "coOl": print("That's Cool!")
elif a == "coOL": print("That's Cool!")
elif a == "cOol": print("That's Cool!")
elif a == "cOoL": print("That's Cool!")
elif a == "cOOl": print("That's Cool!")
elif a == "cOOL": print("That's Cool!")
elif a == "Cool": print("That's Cool!")
elif a == "CooL": print("That's Cool!")
elif a == "CoOl": print("That's Cool!")
elif a == "CoOL": print("That's Cool!")
elif a == "COol": print("That's Cool!")
elif a == "COoL": print("That's Cool!")
elif a == "COOl": print("That's Cool!")
elif a == "COOL": print("That's Cool!")

#fun

elif a == "fun": print("That's Cool!")
elif a == "fuN": print("That's Cool!")
elif a == "fUn": print("That's Cool!")
elif a == "fUN": print("That's Cool!")
elif a == "Fun": print("That's Cool!")
elif a == "FuN": print("That's Cool!")
elif a == "FUn": print("That's Cool!")
elif a == "FUN": print("That's Cool!")

#fine

elif a == "fine": print("That's Cool!")
elif a == "finE": print("That's Cool!")
elif a == "fiNe": print("That's Cool!")
elif a == "fiNE": print("That's Cool!")
elif a == "fIne": print("That's Cool!")
elif a == "fInE": print("That's Cool!")
elif a == "fINe": print("That's Cool!")
elif a == "fINE": print("That's Cool!")
elif a == "Fine": print("That's Cool!")
elif a == "FinE": print("That's Cool!")
elif a == "FiNe": print("That's Cool!")
elif a == "FiNE": print("That's Cool!")
elif a == "FIne": print("That's Cool!")
elif a == "FInE": print("That's Cool!")
elif a == "FINe": print("That's Cool!")
elif a == "FINE": print("That's Cool!")

#Bad fillings

#bad

elif a == "bad": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "baD": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "bAd": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "bAD": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "Bad": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "BaD": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "BAd": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "BAD": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")

#poor

elif a == "poor": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "pooR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "poOr": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "poOR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "pOor": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "pOoR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "pOOr": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "pOOR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "Poor": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "PooR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "PoOr": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "PoOR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "POor": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "POoR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "POOr": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "POOR": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")

#awful

elif a == "awful": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awfuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awfUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awfUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awFul": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awFuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awFUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "awFUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWful": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWfuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWfUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWfUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWFul": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWFuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWFUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "aWFUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "Awful": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwfuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwfUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwfUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwFul": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwFuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwFUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AwFUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWful": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWfuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWfUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWfUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWFul": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWFuL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWFUl": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "AWFUL": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")

#lousy
elif a == "lousy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lousY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "louSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "louSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "loUsy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "loUsY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "loUSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "loUSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOusy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOusY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOuSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOuSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOUsy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOUsY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOUSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "lOUSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "Lousy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LousY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LouSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LouSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LoUsy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LoUsY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LoUSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LoUSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOusy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOusY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOuSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOuSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOUsy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOUsY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOUSy": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")
elif a == "LOUSY": print("Oh, can you tell me what happend?\nYes\nNo\n>>> ")

